spring.config.activate.on-profile: test

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:skeleton
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:skeleton
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

