[libraries]
poi-ooxml = {group = "org.apache.poi", name = "poi-ooxml", version = "5.4.1"}
colo-excel = {group = "com.colosseum", name = "excel", version = "0.0.1"}
colo-starter = {group = "com.colosseum", name = "colo-starter", version = "0.0.1"}

